name: Cargo Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        options: --health-cmd "mysqladmin ping -h 127.0.0.1 -P 3306" --health-interval 5s --health-timeout 2s --health-retries 30
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: actix_web_sample
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v2
      - name: Install diesel_cli
        run: cargo install diesel_cli --no-default-features --features mysql
      - name: Run migrations
        run: diesel migration run
        env:
          DATABASE_URL: mysql://root:root@127.0.0.1:3306/actix_web_sample
      - name: Copy .env file
        run: cp .env.github .env
      - name: Run build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose