on: push
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root:example@localhost:13306/actix_web_sample
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - name: Set up MySQL to prevent SQLx build failure.
        run: docker-compose up -d
        working-directory: ./docker
      - run: cargo install diesel_cli
      - run: diesel migration run
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features